### ISSUE TITLE
Confusion between main and master branches

### ISSUE THREAD

**Issue by pablooliveira** [TREX-CoE/qmckl#19]
Currently there are two principal branches: main and master.
It's not clear which one is the authoritative one. I suggest we pick one and stick with it.

The `main` branch seems to lag behind but some of the links still point to it. For example, the README.md in `master` branch documentation has links that point to the `main` branch instead.

What do you think @scemama ?

Thanks !

**Comment by scemama** [comment]
Yes, main should not exist. It was created because github decided to rename git's master branch in main. I renamed it "master", but main remained. I kill the "main" branch now.

**Comment by pablooliveira** [comment]
Thanks. I fixed the link in the documentation.
