### ISSUE TITLE
Safe functions

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/qmckl#38]
Required for Python interface

**Comment by q-posev** [comment]
Just to clarify: 
SWIG can generate nice Python-adapated wrappers for functions that contain the following pattern in their argument list:
`type * arr, int64_t DIM` where `DIM` specifies the size of the `arr`.  This is particularly handy when coupled to NumPy arrays.

In the currently generated `qmckl.h` file, the additional argument `int64_t DIM` is missing.
