### ISSUE TITLE
FAIL : test_qmckl_local_energy 

### ISSUE THREAD

**Issue by krahmouasy** [TREX-CoE/qmckl#60]
On latest master commit while using icc/ifort 2021.3 + -xCORE-AVX2 + fno-omit-frame-pointer 
I tried to run test-driver directly but didn't manage to have it to work (was always missing one argument apparently ...).

Configure command used : 
`./configure --prefix=$PWD/_install CC=icc FC=ifort CFLAGS="-g -O2 -xCORE-AVX2 -fno-omit-frame-pointer" FCFLAGS="-cpp -g -O2 -xCORE-AVX2 -fno-omit-frame-pointer"`

Resume :
```
qmckl Version 0.1.1  -- Developer mode

Prefix: '/home/kcamus/Trex/qmckl/qmckl/_install'.

CC..............: icc
CPPFLAGS........: 
CFLAGS..........: -g -O2 -xCORE-AVX2 -fno-omit-frame-pointer  
FC..............: ifort
FCLAGS..........: -cpp -g -O2 -xCORE-AVX2 -fno-omit-frame-pointer -nofor-main
LDFLAGS:........: 
LIBS............: -lopenblas -llapack -lopenblas   -ltrexio -lpthread -lm 
USE CHAMELEON...: 

Package features:
   trexio
```

Output extract when running make check (all others tests pass):
```
PASS: tests/test_qmckl_jastrow
./tools/test-driver: line 109: 541134 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: tests/test_qmckl_local_energy
```

Let me know if you need anything specific or if I need to try something.

**Comment by v1j4y** [comment]
Hi @krahmouasy 

Thanks for the report !

I'll have a look tomorrow and try to reproduce the incident. Will report back asap.

Best,
 Vijay

**Comment by v1j4y** [comment]
Hi @krahmouasy the issue is resolved. Please confirm.
